# Copyright 2025 Advanced Micro Devices, Inc.
#
# Licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception

name: Release Llama 3.1 405B FP4 Benchmarking Tests

on:
  workflow_dispatch:
  pull_request:
  push:
   branches:
     - main
  schedule:
    # Weekdays at 11:00 AM UTC = 03:00 AM PST / 04:00 AM PDT
    - cron: "0 11 * * 1-5"

permissions:
  contents: write

concurrency:
  # A PR number if a pull request and otherwise the commit hash. This cancels
  # queued and in-progress runs for the same PR (presubmit) or commit
  # (postsubmit). The workflow name is prepended to avoid conflicts between
  # different workflows.
  group: ${{ github.workflow }}-${{ github.event.number || github.sha }}
  cancel-in-progress: true

jobs:
  test_llama_large:
    if: ${{ github.repository_owner == 'nod-ai' || github.event_name != 'schedule' }}
    timeout-minutes: 240
    name: "Release: Llama 405B FP4 Benchmarking Tests"
    strategy:
      matrix:
        version: [3.11]
      fail-fast: false
    runs-on: linux-mi355-1gpu-ossci-nod-ai
    container:
      image: 'ghcr.io/rocm/no_rocm_image_ubuntu24_04@sha256:405945a40deaff9db90b9839c0f41d4cba4a383c1a7459b28627047bf6302a26'
      options: --ipc host
        --group-add video
        --device /dev/kfd
        --device /dev/dri
        --env-file /etc/podinfo/gha-gpu-isolation-settings
      volumes:
        - /shark-dev:/shark-dev
        - /shark-cache:/shark-cache
    defaults:
      run:
        shell: bash
    env:
      VENV_DIR: ${{ github.workspace }}/.venv
      OFFLINE_SERVING: DISABLED
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: "Setting up Python"
        id: setup_python
        uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5.6.0
        with:
          python-version: ${{matrix.version}}
      - name: Create Python venv
        run: |
           python -m venv ${VENV_DIR}
           source ${VENV_DIR}/bin/activate

      - name: Install pip deps
        run: |
          python -m pip install \
            --index-url https://d2awnip2yjpvqn.cloudfront.net/v2/gfx950-dcgpu/ \
            rocm[libraries,devel]
          sudo apt install -y gfortran
          rocm-sdk path --bin
          rocm-sdk test
          rocm-smi
          rocminfo test
          bash scripts/setenv.sh --nightly-cpu
          pip freeze | grep torch
          mkdir -p output_artifacts
          iree-run-module --list_devices
          pip freeze | grep -E 'iree|shark' > $(pwd)/output_artifacts/version.txt

      - name: Run export and compile
        run: |
          bash scripts/export_and_compile.sh \
             --irpa  /shark-dev/llama3.1/405b/fp4/fp4_2025_07_10_fn.irpa \
             --bs-prefill 4 --bs-decode 8 --dtype llama-405B-FP4

      - name: Validate VMFB Numerics
        run: |
          python -m sharktank.tools.run_llm_vmfb \
            --prompt "Capital of United States and India" \
            --irpa /shark-dev/llama3.1/405b/fp4/fp4_2025_07_10_fn.irpa \
            --vmfb $(pwd)/output_artifacts/output.vmfb \
            --config $(pwd)/output_artifacts/config_attn.json \
            --tokenizer /shark-dev/llama3.1/405b/fp4/tokenizer.json \
            --steps 60 \
            --kv-cache-dtype float8_e4m3fn | tee output_artifacts/run_llm_vmfb.log

      - name: Run IREE Benchmark Module
        run: |
          bash scripts/run_iree_benchmark.sh --bs-prefill 4 --bs-decode 8 \
             --parameters /shark-dev/llama3.1/405b/fp4/fp4_2025_07_10_fn.irpa \
             --model llama-405B-FP4
          python scripts/utils.py \
            --combine-json $(pwd)/output_artifacts/benchmark_module \
            --output-json $(pwd)/output_artifacts/consolidated_benchmark.json \
            --append-isl

      - name: Run online serving
        run: |
          cd shortfin
          bash ../scripts/run_serving.sh \
             --irpa /shark-dev/llama3.1/405b/fp4/fp4_2025_07_10_fn.irpa \
             --tokenizer_json /shark-dev/llama3.1/405b/fp4/tokenizer.json \
             --vmfb $(pwd)/output_artifacts/output.vmfb \
             --model_config $(pwd)/output_artifacts/config_attn.json \
             --port 8900 | tee ../output_artifacts/serving.log
          cd ..

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@4f9cc6602d3f66b9c108549d475ec49e8ef4d45e # v4.0.0
        with:
          github_token: ${{ secrets.SHARK_PLATFORM_GH_TOKEN }}
          publish_dir: ./out/llm/llama/benchmark
          destination_dir: ./llm/llama/benchmark
          keep_files: true

      - name: Upload llama executable files
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: llama-files
          path: ${{ github.workspace }}/${{ steps.date.outputs.date }}

      - name: Upload log files
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02
        with:
          name: llama-logs
          path: |
            output_artifacts/consolidated*.json
            output_artifacts/*.log
            output_artifacts/version.txt

      - name: Cleanup output artifacts
        run: |
            rm -rf output_artifacts
            test ! -d output_artifacts && echo "Output artifacts are removed"

  # New job to push logs to shark-ai-reports repository
  push_logs:
    name: "Push log llama 405B FP4"
    needs: [ test_llama_large ]
    runs-on: ubuntu-24.04
    steps:
    - name: Download log artifacts
      uses: actions/download-artifact@v4
      with:
        name: llama-logs
        path: logs

    - name: Checkout Target Repo
      uses: actions/checkout@v4
      with:
        repository: nod-ai/shark-ai-reports
        token: ${{ secrets.SHARK_AI_REPORTS_GITHUB_TOKEN }}
        path: shark-ai-reports

    - name: Push artifacts
      run: |
        git config --global user.name "GitHub Actions Bot"
        git config --global user.email ""
        date=$(date -u +'%Y-%m-%d')
        mkdir -p "shark-ai-reports/$date/llama-405b-fp4-logs"
        cp -v logs/*.json "shark-ai-reports/$date/llama-405b-fp4-logs"
        cp -v logs/*.log "shark-ai-reports/$date/llama-405b-fp4-logs"
        cp -v logs/version.txt "shark-ai-reports/$date/llama-405b-fp4-logs"
        cd shark-ai-reports
        git pull
        git add $date
        git commit -m "Add CI Llama 405B FP4 logs on $(date -u +'%Y-%m-%d')"
        git push origin main
        rm -rf ../logs
