# Copyright 2025 Advanced Micro Devices, Inc.
#
# Licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception

name: Harness run Llama 3.1 8B FP16

on:
  workflow_dispatch:
  pull_request:
  push:
   branches:
     - main
  schedule:
    # Nightly at 12:00 AM UTC
    - cron: "0 0 * * *"

permissions:
  contents: write

concurrency:
  # A PR number if a pull request and otherwise the commit hash. This cancels
  # queued and in-progress runs for the same PR (presubmit) or commit
  # (postsubmit). The workflow name is prepended to avoid conflicts between
  # different workflows.
  group: ${{ github.workflow }}-${{ github.event.number || github.sha }}
  cancel-in-progress: true

jobs:
  mlperf_llama_benchmark:
    if: ${{ github.repository_owner == 'nod-ai' || github.event_name != 'schedule' }}
    timeout-minutes: 360
    name: "MLPerf: Llama 3.1 8B FP16 Nightly harness"
    strategy:
      matrix:
        version: [3.11]
      fail-fast: false
    runs-on: linux-mi325-1gpu-ossci-nod-ai
    defaults:
      run:
        shell: bash
    env:
      VENV_DIR: ${{ github.workspace }}/.venv
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Get Current Date And Check if it is serving day
        id: date
        run: |
          echo "date=$(date -u +'%Y-%m-%d')" >> "$GITHUB_OUTPUT"

      - name: "Setting up Python"
        id: setup_python
        uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5.6.0
        with:
          python-version: ${{matrix.version}}

      - name: Create Python venv
        run: |
           python -m venv ${VENV_DIR}
           source ${VENV_DIR}/bin/activate

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@e468171a9de216ec08956ac3ada2f0791b6bd435 # v3.11.1

      - name: Checkout harness repo
        uses: actions/checkout@v4
        with:
          repository: nod-ai/2024q2-sdxl-mlperf-sprint
          ref: mi355_llama_working_harness_v1
          token: ${{ secrets.SHARK_AI_REPORTS_GITHUB_TOKEN }}
          path: 2024q2-sdxl-mlperf-sprint

      - name: Build docker image
        run: |
          echo "Building docker image ..."
          cd 2024q2-sdxl-mlperf-sprint
          docker build --platform linux/amd64 --tag mlperf_llama:8b --file LLAMA_inference/llama_harness.dockerfile .


      - name: Run docker image
        run: |
            echo "Running docker image ..."
            ./LLAMA_inference/run_docker_8b.sh

      - name: Download dataset
        run: |
          ./download_dataset.sh

      - name: Precompile model 8b
        run: |
          ./precompile_models_8b_fp16_nightly.sh --irpa-path /shark-dev/fp16/llama3.1_8b_fp16_tp1.irpa

      - name: Run harness
        run: |
          echo "Running harness ..."
          # reduces min time duration to 11 seconds just to enable ci
          sed -i 's/600000/11000/g' user.conf
          mkdir -p output_artifacts
          ./run_offline_8b_nightly.sh --shortfin-config shortfin_8b_config_nightly.json --verbose |& tee output_artifacts/run_offline.stdout.log

      - name: Upload llama executable files
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: llama-files
          path: ${{ github.workspace }}/${{ steps.date.outputs.date }}

      - name: Upload log files
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02
        with:
          name: llama-logs
          path: |
            output_artifacts/*.log

      - name: Cleanup output artifacts
        run: |
            rm -rf output_artifacts
            test ! -d output_artifacts && echo "Output artifacts are removed"

  # New job to push logs to shark-ai-reports repository
  push_logs:
    name: "Push log llama 8B FP16"
    needs: [ mlperf_llama_benchmark ]
    runs-on: ubuntu-24.04
    steps:
    - name: Download log artifacts
      uses: actions/download-artifact@v4
      with:
        name: llama-logs
        path: logs

    - name: Checkout Target Repo
      uses: actions/checkout@v4
      with:
        repository: nod-ai/shark-ai-reports
        token: ${{ secrets.SHARK_AI_REPORTS_GITHUB_TOKEN }}
        path: shark-ai-reports

    - name: Push artifacts
      run: |
        git config --global user.name "GitHub Actions Bot"
        git config --global user.email ""
        date=$(date -u +'%Y-%m-%d')
        log_dir="shark-ai-reports/$date/llama-8b-fp16-harness-logs"
        mkdir -p $log_dir
        #cp -v logs/*.json $log_dir
        cp -v logs/*.log $log_dir
        cd shark-ai-reports
        git pull
        git add $date
        git commit -m "Add CI Llama 8B FP16 harness logs on $(date -u +'%Y-%m-%d')"
        git push origin main
        rm -rf ../logs
