# Copyright 2025 Advanced Micro Devices, Inc.
#
# Licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception

name: Harness run Llama 3.1 8B FP16

on:
  workflow_dispatch:
  pull_request:
  push:
   branches:
     - main
  schedule:
    # Nightly at 12:00 AM UTC
    - cron: "0 0 * * *"

permissions:
  contents: write

concurrency:
  # A PR number if a pull request and otherwise the commit hash. This cancels
  # queued and in-progress runs for the same PR (presubmit) or commit
  # (postsubmit). The workflow name is prepended to avoid conflicts between
  # different workflows.
  group: ${{ github.workflow }}-${{ github.event.number || github.sha }}
  cancel-in-progress: true

jobs:
  mlperf_llama_benchmark:
    if: ${{ github.repository_owner == 'nod-ai' || github.event_name != 'schedule' }}
    timeout-minutes: 360
    name: "MLPerf: Llama 3.1 8B FP16 Nightly Benchmark"
    strategy:
      matrix:
        version: [3.11]
      fail-fast: false
    runs-on: linux-mi325-1gpu-ossci-nod-ai
    defaults:
      run:
        shell: bash
    env:
      VENV_DIR: ${{ github.workspace }}/.venv
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Get Current Date And Check if it is serving day
        id: date
        run: |
          echo "date=$(date -u +'%Y-%m-%d')" >> "$GITHUB_OUTPUT"

          if [ "$(date -u +%u)" = "7" ]; then
            echo "IS_SERVING_DAY=true" >> $GITHUB_ENV
          else
            echo "IS_SERVING_DAY=false" >> $GITHUB_ENV
          fi

      - name: "Setting up Python"
        id: setup_python
        uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5.6.0
        with:
          python-version: ${{matrix.version}}

      - name: Create Python venv
        run: |
           python -m venv ${VENV_DIR}
           source ${VENV_DIR}/bin/activate

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@e468171a9de216ec08956ac3ada2f0791b6bd435 # v3.11.1

          #- name: Pull SGLang Image (Had issues with sglang:v0.3.5.post2-rocm620)
      - name: Build docker image
        run: |
          echo "Build docker"

      - name: Run docker image
        run: |
            echo "Run docker image"

      - name: Run harness
        run: |
          echo "Run harness"

  # New job to push logs to shark-ai-reports repository
  push_logs:
    name: "Push log llama 8B FP16"
    needs: [ test_llama_large ]
    runs-on: ubuntu-24.04
    steps:
    - name: Download log artifacts
      uses: actions/download-artifact@v4
      with:
        name: llama-logs
        path: logs

    - name: Checkout Target Repo
      uses: actions/checkout@v4
      with:
        repository: nod-ai/shark-ai-reports
        token: ${{ secrets.SHARK_AI_REPORTS_GITHUB_TOKEN }}
        path: shark-ai-reports

    - name: Push artifacts
      run: |
        git config --global user.name "GitHub Actions Bot"
        git config --global user.email ""
        date=$(date -u +'%Y-%m-%d')
        log_dir="shark-ai-reports/$date/llama-8b-fp16-harness-logs"
        mkdir -p $log_dir
        cp -v logs/*.json $log_dir
        cp -v logs/*.log $log_dir
        cd shark-ai-reports
        git pull
        git add $date
        git commit -m "Add CI Llama 8B FP16 harness logs on $(date -u +'%Y-%m-%d')"
        git push origin main
        rm -rf ../logs
