# Copyright 2025 Advanced Micro Devices, Inc.
#
# Licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception

name: Sync CI Data Files

on: workflow_dispatch

jobs:
  cleanup:
    name: "Sync CI Data Files"
    runs-on: linux-mi325-1gpu-ossci-nod-ai
    defaults:
      run:
        shell: bash
    env:
      AZ_PUBLIC_KEY: ${{ secrets.SHARKPUBLIC_AZ_PUBLIC_KEY }}
    steps:
      -name: Sync data files
      env:
        SAS_TOKEN: ${{ inputs.sas_token || 90 }}
      run: |
        azcopy sync "https://sharkpublic.blob.core.windows.net/ossci/ossci-models" /shark-dev/ossci-models --account-key ${AZ_PUBLIC_KEY}
