# Copyright 2025 Advanced Micro Devices, Inc.
#
# Licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception

name: Release SDXL and FLUX Shortfin Serving Tests

on:
  workflow_dispatch:
  push:
    branches:
      - "bump-torch-2.6"
  schedule:
  # Weekdays at 11:00 AM UTC = 03:00 AM PST / 04:00 AM PDT
  - cron: "0 9 * * 1-5"

concurrency:
  # A PR number if a pull request and otherwise the commit hash. This cancels
  # queued and in-progress runs for the same PR (presubmit) or commit
  # (postsubmit). The workflow name is prepended to avoid conflicts between
  # different workflows.
  group: ${{ github.workflow }}-${{ github.event.number || github.sha }}
  cancel-in-progress: true

permissions:
  contents: write

jobs:
  test_sdxl_flux_serving:
    if: ${{ github.repository_owner == 'nod-ai' || github.event_name != 'schedule' }}
    timeout-minutes: 240
    name: "Release: SDXL and Flux Shortfin Serving Tests"
    strategy:
      matrix:
        version: [ 3.11 ]
      fail-fast: false
    runs-on: linux-mi300-1gpu-ossci-nod-ai
    defaults:
      run:
        shell: bash
    env:
      VENV_DIR: ${{ github.workspace }}/.venv
      HF_HOME: "/shark-cache/data/huggingface"
      HF_TOKEN: ${{ secrets.HF_FLUX_TOKEN }}
    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

    - name: "Setting up Python"
      id: setup_python
      uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5.6.0
      with:
        python-version: ${{matrix.version}}
    - name: Create Python venv
      run: |
        python -m venv ${VENV_DIR}
        source ${VENV_DIR}/bin/activate

    - name: Install pip deps
      run: bash scripts/setenv.sh --nightly

    - name: Run SDXL (precompiled)
      run: |
        bash scripts/run_sdxl_flux.sh \
          --model sdxl \
          --build_preference precompiled

    - name: Run Flux-Dev (precompiled)
      run: |
        bash scripts/run_sdxl_flux.sh \
          --model flux_dev \
          --build_preference precompiled \
          --hf-token ${HF_TOKEN}

    - name: Run Flux-Dev (compile)
      run: |
        bash scripts/run_sdxl_flux.sh \
          --model flux_dev \
          --build_preference compile \
          --hf-token ${HF_TOKEN}

    - name: Run Flux-Schnell (precompiled)
      run: |
        bash scripts/run_sdxl_flux.sh \
          --model flux_schnell \
          --build_preference precompiled \
          --hf-token ${HF_TOKEN}

    - name: Run Flux-Schnell (compile)
      run: |
        bash scripts/run_sdxl_flux.sh \
          --model flux_schnell \
          --build_preference compile \
          --hf-token ${HF_TOKEN}
